language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# 권한 설정
before_install:
  - chmod +x ./gradlew

after_deploy:
  - "ls /home/travis/build/awse2050/Commerce-JPA/src/main/resources"

after_script:
  - "ls /home/travis/build/awse2050/Commerce-JPA/src/main/resources"

# CI 실행 완료시 메일로 알림
notifications:
  email:
    recipients:
      - kyh3964@naver.com
