language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# 권한 설정
before_install:
  - chmod +x ./gradlew

# test
after_script:
  - "ls /home/travis/build/awse2050/Commerce-JPA/src/main/resources"
  - "cat /home/travis/build/awse2050/Commerce-JPA/src/main/resources/application.properties"
  - "cat /home/travis/build/awse2050/Commerce-JPA/src/main/resources/application-pay.properties"
  - "cat /home/travis/build/awse2050/Commerce-JPA/src/main/resources/application-real.properties"
  - "cat /home/travis/build/awse2050/Commerce-JPA/src/main/resources/application-real-db.properties"
  - "/home/travis/build/awse2050/Commerce-JPA/build/reports/tests/test/index.html"

# CI 실행 완료시 메일로 알림
notifications:
  email:
    recipients:
      - kyh3964@naver.com
